services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cash_lens_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: /bin/sh -c "mix deps.get && mix ecto.setup && mix phx.server"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/cash_lens_dev
      - SECRET_KEY_BASE=sY8Gq6f0Xf8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f
      - PHX_HOST=0.0.0.0
      - WATCHMAN_DISABLE=true
    depends_on:
      - db

volumes:
  postgres_data:
