sonar.projectKey=heitorpolidoro_cash_lens
sonar.organization=heitorpolidoro

# Path is relative to the sonar-project.properties file.
sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**/*_test.exs

# Encoding of the source code.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/_build/**, **/deps/**, **/assets/node_modules/**

# Elixir specific configurations
sonar.coverageReportPaths=cover/excoveralls.xml
sonar.lang.patterns.text=**/*.ex,**/*.exs
