sonar.projectKey=heitorpolidoro_cash_lens
sonar.organization=heitorpolidoro

# Path is relative to the sonar-project.properties file.
sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**/*_test.exs

# Encoding of the source code.
sonar.sourceEncoding=UTF-8

# Elixir specific configurations
sonar.coverageReportPaths=cover/excoveralls.xml

# JavaScript specific configurations
sonar.javascript.lcov.reportPaths=assets/cover/lcov.info
