sonar.projectKey=heitorpolidoro_cash_lens
sonar.organization=heitorpolidoro

# Path is relative to the sonar-project.properties file.
sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**/*_test.exs

# Encoding of the source code.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/_build/**, **/deps/**, **/assets/node_modules/**, lib/cash_lens.ex, lib/cash_lens/mailer.ex, lib/cash_lens/repo.ex, lib/cash_lens_web/endpoint.ex, lib/cash_lens_web/gettext.ex, lib/cash_lens_web/telemetry.ex, lib/cash_lens_web/controllers/page_html.ex, lib/cash_lens_web/controllers/error_html.ex, lib/cash_lens_web/controllers/error_json.ex, lib/cash_lens_web.ex, lib/cash_lens/application.ex, lib/cash_lens_web/live/automation_live/bulk_ignore.ex, lib/cash_lens_web/live/transaction_live/transfer_link_component.ex, lib/cash_lens_web/live/balance_live/index.ex, lib/cash_lens_web/live/balance_live/form.ex, lib/cash_lens_web/formatters.ex, lib/cash_lens_web/live/category_live/index.ex, lib/cash_lens_web/live/category_live/form.ex, lib/cash_lens_web/live/reimbursement_live/index.ex, lib/cash_lens_web/live/transaction_live/reimbursement_link_component.ex, lib/cash_lens_web/components/core_components.ex, lib/cash_lens_web/router.ex, test/support/data_case.ex, test/support/conn_case.ex, lib/cash_lens_web/live/transaction_live/form.ex, lib/cash_lens_web/live/transaction_live/index.ex, lib/cash_lens_web/live/account_live/form.ex, lib/cash_lens_web/live/account_live/index.ex, lib/cash_lens_web/live/admin_database_live.ex, lib/cash_lens_web/components/layouts.ex

# Elixir specific configurations
sonar.coverageReportPaths=cover/excoveralls.xml
sonar.lang.patterns.text=**/*.ex,**/*.exs
