name: "Elixir CI"

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    uses: heitorpolidoro/.github/.github/workflows/elixir-ci.yml@master
    with:
      postgres-db: "cash_lens_test"
      sonar-project-key: "heitorpolidoro_cash_lens"
    secrets: inherit # pragma: allowlist secret
